let selectedMode="",selectedCompetition="",selectedTeam="",selectedCountry="",selectedEra="",squad=[],currentMatch=1,currentStreak=0,bestStreak=0,careerWins=0,careerLosses=0,careerDraws=0,history=[];const ERA_LIST=["1930s","1940s","1950s","1960s","1970s","1980s","1990s","2000s","2010s","2020s"],$=id=>document.getElementById(id);
function init(){const modes=[["Mens","🏏 Men's"],["Womens","🏏 Women's"]];$("modeButtons").innerHTML=modes.map(m=>'<button class="mode-button">'+m[1]+"</button>").join("");document.querySelectorAll("#modeButtons .mode-button").forEach((b,i)=>b.onclick=()=>startGame(modes[i][0]));$("competitionButtons").innerHTML=Object.entries(competitionData).map(([k,v])=>'<button class="competition-button">'+v.label+"</button>").join("");document.querySelectorAll("#competitionButtons .competition-button").forEach((b,i)=>b.onclick=()=>chooseCompetition(Object.keys(competitionData)[i]));$("eraButtons").innerHTML=ERA_LIST.map(e=>'<button class="era-button">'+e+"</button>").join("");document.querySelectorAll("#eraButtons .era-button").forEach((b,i)=>b.onclick=()=>chooseEra(ERA_LIST[i]));$("resetGameBtn").onclick=resetAll;document.querySelectorAll(".back-btn").forEach(b=>b.onclick=()=>show(b.dataset.back));updateHome()}
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.add("hidden"));$(id).classList.remove("hidden");window.scrollTo(0,0)}
function startGame(mode){selectedMode=mode;show("competition")}
function chooseCompetition(c){selectedCompetition=c;renderTeams();show("teams")}
function renderTeams(){const data=competitionData[selectedCompetition];$("teamTitle").textContent="Choose your team";$("teamButtons").innerHTML=data.teams.map(t=>'<button class="team-button">'+teamEmoji(t)+" "+t+"</button>").join("");document.querySelectorAll("#teamButtons .team-button").forEach((b,i)=>b.onclick=()=>pickTeam(data.teams[i]));$("randomTeamBtn").onclick=()=>{const t=data.teams[Math.floor(Math.random()*data.teams.length)];pickTeam(t)}}
function teamEmoji(t){const c=teamData[t]?.country;return c==="Australia"?"🇦🇺":c==="India"?"🇮🇳":c==="England"?"🏴":c==="South Africa"?"🇿🇦":c==="New Zealand"?"🇳🇿":c==="Pakistan"?"🇵🇰":c==="Sri Lanka"?"🇱🇰":c==="West Indies"?"🏝️":"🏏"}
function pickTeam(t){selectedTeam=t;selectedCountry=teamData[t]?.country||t;show("era")}
function chooseEra(e){selectedEra=e;squad=[];renderDraft();show("draft")}
function getPool(){const raw=playerDatabase[selectedCountry]||[];const exact=raw.filter(p=>p[5].includes(selectedEra));let pool=exact.slice();if(pool.length<14)raw.slice().sort((a,b)=>distanceToEra(a)-distanceToEra(b)).forEach(p=>{if(!pool.includes(p))pool.push(p)});return pool.slice(0,20).map(p=>buildPlayer(selectedCountry,p))}
function distanceToEra(p){const idx=ERA_LIST.indexOf(selectedEra);return Math.min(...p[5].map(e=>Math.abs(ERA_LIST.indexOf(e)-idx)))}
function renderDraft(){ $("draftTeam").textContent=selectedTeam+" • "+selectedMode;$("draftEra").textContent=selectedEra;const pool=getPool(),selected=new Set(squad.map(p=>p.name));$("playerCards").innerHTML=pool.map(p=>'<div class="card player-card"><div class="role">'+p.role+'</div><h3>'+p.name+'</h3><div class="ratings"><span>BAT<b>'+p.batting+'</b></span><span>BOWL<b>'+p.bowling+'</b></span><span>FIELD<b>'+p.fielding+'</b></span></div><button class="select-button" '+(selected.has(p.name)?"disabled":"")+' onclick="selectPlayer(\''+p.name.replace(/'/g,"\\'")+"\')">"+(selected.has(p.name)?"SELECTED":"SELECT")+"</button></div>").join("");$("draftCount").textContent=squad.length+"/11";$("selectedPlayers").innerHTML=squad.length?'<b>Your XI</b><div class="selected-list">'+squad.map((p,i)=>'<span class="pill">'+(i+1)+". "+p.name+"</span>").join("")+"</div>":"<b>Your XI</b><p class="muted">Pick 11 players and balance the roles.</p>";const bowl=squad.filter(p=>p.role==="Bowler").length,bat=squad.filter(p=>p.role==="Batter").length,wk=squad.filter(p=>p.role==="Wicketkeeper").length;$("roleWarning").textContent=squad.length===11?(bowl<3?"⚠️ Consider 3+ bowlers.":wk<1?"⚠️ No wicketkeeper selected.":"✅ XI ready."):"";$("startChallengeBtn").classList.toggle("hidden",squad.length!==11);$("startChallengeBtn").onclick=startChallenge}
function selectPlayer(name){const p=getPool().find(x=>x.name===name);if(!p||squad.length>=11||squad.some(x=>x.name===name))return;squad.push(p);renderDraft()}
function startChallenge(){currentMatch=1;currentStreak=0;history=[];showMatchScreen()}
function difficulty(){return Math.min(.16,(currentMatch-1)*.012)}
function squadStrength(){if(!squad.length)return 50;const bat=squad.reduce((s,p)=>s+p.batting,0)/squad.length,bowl=squad.reduce((s,p)=>s+p.bowling,0)/squad.length,field=squad.reduce((s,p)=>s+p.fielding,0)/squad.length,wk=squad.some(p=>p.role==="Wicketkeeper")?4:-4,balance=(squad.filter(p=>p.role==="Bowler").length>=3?3:0)+(squad.filter(p=>p.role==="Batter").length>=4?3:0);return bat*.4+bowl*.4+field*.2+wk+balance}
function opponentName(){const all=["Australia","India","England","South Africa","New Zealand","Pakistan","Sri Lanka","West Indies"],p=all.filter(x=>x!==selectedCountry);return p[Math.floor(Math.random()*p.length)]}
function showMatchScreen(){show("match");const pct=Math.min(100,currentStreak/20*100),opp=opponentName();$("matchPanel").innerHTML='<div class="card"><div class="match-top"><div><div class="eyebrow">20-MATCH CHALLENGE</div><h2>Match '+currentMatch+'/20</h2></div><strong>🔥 '+currentStreak+'/20</strong></div><div class="progress"><div style="width:'+pct+'%"></div></div></div><div class="card scoreboard"><div><small>'+selectedTeam+'</small><div class="score">XI</div></div><div class="vs">VS</div><div><small>'+opp+'</small><div class="score">🏏</div></div></div><div class="card"><h3>Match plan</h3><p class="muted">XI strength: <b>'+Math.round(squadStrength())+'</b>. The challenge gets harder as the streak grows.</p><div class="match-actions"><button class="gold" onclick="playMatch()">▶ PLAY</button><button onclick="showSquad()">👥 XI</button></div><button class="wide" onclick="quickSim()">⏩ Quick simulate</button></div>'}
function showSquad(){renderDraft();show("draft")}
function playMatch(){const opp=opponentName(),strength=squadStrength(),base=.58+(strength-75)/180-difficulty()+(selectedCompetition==="Test"?.02:0),roll=Math.random();let result=roll<Math.max(.25,Math.min(.9,base))?"WIN":roll<.96?"LOSS":"DRAW";if(result==="DRAW"&&selectedCompetition!=="Test")result="LOSS";const your=Math.max(80,Math.floor(190+Math.random()*150+(strength-75)*1.2)),oppScore=result==="WIN"?Math.max(70,your-Math.floor(8+Math.random()*65)):result==="LOSS"?your+Math.floor(5+Math.random()*65):your;history.push({n:currentMatch,opp,result,your,oppScore});if(result==="WIN"){currentStreak++;careerWins++}else if(result==="LOSS"){currentStreak=0;careerLosses++}else careerDraws++;bestStreak=Math.max(bestStreak,currentStreak);updateHome();renderResult(history[history.length-1])}
function quickSim(){playMatch()}
function renderResult(m){const win=m.result==="WIN",draw=m.result==="DRAW",cls=win?"result-win":draw?"result-draw":"result-loss",margin=Math.abs(m.your-m.oppScore);$("matchPanel").innerHTML='<div class="card '+cls+'"><div class="eyebrow">MATCH '+m.n+'</div><h2>'+(win?"🏆 YOU WIN!":draw?"🤝 DRAW":"❌ DEFEAT")+'</h2><div class="scoreboard"><div><small>'+selectedTeam+'</small><div class="score">'+m.your+'</div></div><div class="vs">-</div><div><small>'+m.opp+'</small><div class="score">'+m.oppScore+'</div></div></div><p><b>'+(win?"Won by ":"Lost by ")+margin+' runs</b></p></div><div class="card"><h3>🔥 Streak: '+currentStreak+'/20</h3><p class="muted">Best: '+bestStreak+' • Career wins: '+careerWins+' • Losses: '+careerLosses+'</p>'+(win&&currentStreak>=20?'<button class="gold wide" onclick="champion()">🏆 YOU BEAT 20!</button>':m.result==="LOSS"?'<button class="gold wide" onclick="restartChallenge()">🔄 Try again</button>':'<button class="gold wide" onclick="nextMatch()">▶ Next match</button>')+'<button class="wide" onclick="viewHistory()">📋 Match history</button></div>'}
function nextMatch(){if(currentStreak>=20)champion();else{currentMatch++;showMatchScreen()}}
function restartChallenge(){currentMatch=1;currentStreak=0;history=[];showMatchScreen()}
function champion(){$("matchPanel").innerHTML='<div class="card result-win" style="text-align:center"><div class="trophy">🏆</div><h2>YOU BEAT 20!</h2><p>You completed the 20-match streak.</p><button class="gold wide" onclick="restartChallenge()">Run it back</button><button class="wide" onclick="resetAll()">New XI</button></div>'}
function viewHistory(){const rows=history.map(m=>'<div class="history-row"><span>Match '+m.n+' • '+m.opp+'</span><b>'+m.result+' '+m.your+'-'+m.oppScore+'</b></div>').join("");$("matchPanel").insertAdjacentHTML("beforeend",'<div class="card history"><h3>📋 History</h3>'+rows+"</div>")}
function resetAll(){selectedMode=selectedCompetition=selectedTeam=selectedCountry=selectedEra="";squad=[];currentMatch=1;currentStreak=0;history=[];show("home");updateHome()}
function updateHome(){$("homeStreak").textContent=currentStreak;$("homeBest").textContent=bestStreak;$("homeWins").textContent=careerWins}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();