const teamData={
"Adelaide Strikers":{country:"Australia",pool:"Adelaide Strikers"},
"Brisbane Heat":{country:"Australia",pool:"Brisbane Heat"},
"Hobart Hurricanes":{country:"Australia",pool:"Hobart Hurricanes"},
"Melbourne Renegades":{country:"Australia",pool:"Melbourne Renegades"},
"Melbourne Stars":{country:"Australia",pool:"Melbourne Stars"},
"Perth Scorchers":{country:"Australia",pool:"Perth Scorchers"},
"Sydney Sixers":{country:"Australia",pool:"Sydney Sixers"},
"Sydney Thunder":{country:"Australia",pool:"Sydney Thunder"},
"Chennai Super Kings":{country:"India",pool:"Chennai Super Kings"},
"Delhi Capitals":{country:"India",pool:"Delhi Capitals"},
"Gujarat Titans":{country:"India",pool:"Gujarat Titans"},
"Kolkata Knight Riders":{country:"India",pool:"Kolkata Knight Riders"},
"Lucknow Super Giants":{country:"India",pool:"Lucknow Super Giants"},
"Mumbai Indians":{country:"India",pool:"Mumbai Indians"},
"Punjab Kings":{country:"India",pool:"Punjab Kings"},
"Rajasthan Royals":{country:"India",pool:"Rajasthan Royals"},
"Royal Challengers Bengaluru":{country:"India",pool:"Royal Challengers Bengaluru"},
"Sunrisers Hyderabad":{country:"India",pool:"Sunrisers Hyderabad"},
"Australia":{country:"Australia",pool:"Australia"},
"India":{country:"India",pool:"India"},
"England":{country:"England",pool:"England"},
"South Africa":{country:"South Africa",pool:"South Africa"},
"New Zealand":{country:"New Zealand",pool:"New Zealand"},
"Pakistan":{country:"Pakistan",pool:"Pakistan"},
"Sri Lanka":{country:"Sri Lanka",pool:"Sri Lanka"},
"West Indies":{country:"West Indies",pool:"West Indies"}
};